version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: my-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
   #volumes:
   #  - ./data/mongo:/data/db

#  app:
#    build: .
#    container_name: my-go-app
#    restart: always
#    depends_on:
#      - mongo
#      - keycloak
#    environment:
#      MONGO_URI: mongodb://admin:secret123@mongo:27017
#      KEYCLOAK_URL: http://keycloak:8080/realms/drones-monitor
#      FRONT_URL: http://localhost:5173
#    ports:
#      - "8080:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    ports:
      - "8081:8080"
