# Общая внутренняя сеть для сервисов
networks:
  web:
    external: false

services:
  # ============================
  # MongoDB
  # ============================
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    env_file: [.env]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
    - "27017:27017"
    networks: [web]

  # ============================
  # Keycloak
  # ============================
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    # Для удобства импорта оставляем start-dev + --import-realm.
    # За обратным прокси безопасно, публичный TLS терминирует Caddy.
    command: >
      start-dev
      --import-realm
      --http-enabled=true
      --http-port=8080
      --hostname auth.drones-monitor.ru
      --proxy edge
    env_file: [.env]
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: auth.drones-monitor.ru
      KC_PROXY: edge
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    expose:
      - "8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/realms/master/.well-known/openid-configuration || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 10
    networks: [web]